version: "3"


services:
  oracle18:
    image: oracle-xe:18c
  
  django_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - oracle18

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app

volumes:
  .:
  static:
